services:
  - type: web
    name: swayam-portfolio
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn swayam_portfolio.wsgi"
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-secure-secret-key
      - key: PYTHON_VERSION
        value: 3.11
      - key: DEBUG
        value: False
