# Generated by Django 5.2.3 on 2025-07-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="long_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
