# Generated by Django 5.2.3 on 2025-07-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_about_address_about_age_about_email_about_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("short_description", models.TextField()),
                ("icon", models.CharField(max_length=100)),
            ],
        ),
    ]
