# Generated by Django 5.2.3 on 2025-07-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
