# Generated by Django 5.2.3 on 2025-07-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_booking"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "greeting",
                    models.CharField(default="Hello, It's Me", max_length=100),
                ),
                ("name", models.CharField(max_length=100)),
                ("subheading", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("github", models.URLField(blank=True, null=True)),
                ("linkedin", models.URLField(blank=True, null=True)),
                ("twitter", models.URLField(blank=True, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("cv", models.FileField(blank=True, null=True, upload_to="cv/")),
                ("image", models.ImageField(upload_to="hero/")),
            ],
        ),
    ]
