# Generated by Django 5.2.3 on 2025-07-14 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_hero"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hero",
            name="subheading",
        ),
    ]
