# Generated by Django 5.2.3 on 2025-07-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_remove_hero_subheading"),
    ]

    operations = [
        migrations.AddField(
            model_name="hero",
            name="tagline",
            field=models.TextField(
                default="Web Developer, Designer",
                help_text="Comma-separated job roles for typing effect",
            ),
        ),
    ]
